### ISSUE TITLE
Ridurre numero caratteri nome cliente nel generatore di csv per RouteXL

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#80]
Sarebbe utile se anziché copiare l'intero nome cliente, si limitasse **ai primi 25 caratteri**.

Questo perché l'elenco delle consegne messe in ordine da RouteXL lo copiamo e incolliamo poi dentro al file che stampiamo e diamo agli autisti (Maschera giro).

In questo documento la casella dedicata al nome cliente non è grandissima, e quando i nomi sono molto lunghi si rimpicciolisce in automatico.

Grazie.

**Comment by LukeSavefrogs** [comment]
Ciao,
è già possibile.

E' infatti sufficiente modificare la voce nel file di configurazione `options.output.csv_template` modificando il [formato di formattazione](https://docs.python.org/3/library/string.html#formatstrings) dei campi desiderati... 

## Esempio
**Prima**: 
```toml
[options.output]
csv_template = "@{CustomerName} {CustomerCode}@{eval_IndirizzoSpedizione} {eval_CAPSpedizione} {eval_CittaSpedizione}(20){eval_intervalloSpedizione}^{eval_pesoSpedizione}^"
```
**Dopo**:
```toml
[options.output]
csv_template = "@{CustomerName:.2} {CustomerCode}@{eval_IndirizzoSpedizione:.5} {eval_CAPSpedizione} {eval_CittaSpedizione}(20){eval_intervalloSpedizione}^{eval_pesoSpedizione}^"
```
**Risultato**:
```
@CA 11520@VIA E 00124 ROMA(20)09:00>>19:00^0,00^
@CI 02234@VIA D 00125 ROMA(20)09:00>>19:00^0^
@CO 03405@VIA D 00071 POMEZIA(20)09:00>>19:00^0^
@IM 09881@VIA R 00040 ARDEA(20)09:00>>19:00^180,00^
@LE 09017@VIA P 00124 ROMA(20)09:00>>19:00^0^
@MA 09756@VIA V 00126 ROMA(20)09:00>>19:00^0^
@TI 03484@VIA D 00128 ROMA(20)09:00>>19:00^0^
@TI 10940@VIALE 00127 ROMA(20)09:00>>19:00^0^
```

### Spiegazione
Usando la sintassi `{variabileFORMATO}` (es. `{CustomerName:^20}`) è possibile formattare tutti i campi come meglio si desidera.
Alcuni esempi utili:
- `{variabile:.5}`: Tronca il testo a 5 lettere
- `{variabile:^20}`: Centra il testo con degli spazi fino a raggiungere una una larghezza di 20 caratteri (es. `        TEST       `)
- `{variabile:#^20}`: Centra il testo con il carattere `#` fino a raggiungere una una larghezza di 20 caratteri (es. `########TEST########`)

#### Fonti utili
- [Cheatsheet 1](https://kapeli.com/cheat_sheets/Python_Format_Strings.docset/Contents/Resources/Documents/index)
- [Cheatsheet 2](https://fstring.help/cheat/)


## ✨ Soluzione
Nel tuo caso dovresti modificare solamente il formato con cui viene mostrato il contenuto della variabile `CustomerName`, limitando a massimo 25 caratteri. Come abbiamo visto sopra possiamo fare questo con `{variabile:.25}`...

La configurazione andrà quindi aggiornata così:
```toml
csv_template = "@{CustomerName:.25} {CustomerCode}@{eval_IndirizzoSpedizione} {eval_CAPSpedizione} {eval_CittaSpedizione}(20){eval_intervalloSpedizione}^{eval_pesoSpedizione}^"
```
